import Config

# For development, we disable any cache and enable
# debugging and code reloading.

# Configure your database
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :harpoon, Harpoon.Repo,
  database: "priv/data/harpoon_dev.sqlite",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :harpoon, HarpoonWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "UUB23U6FQrnyVOhZzbgdwtHnXOfO0NLvcoCNdUMCVNGHUeiBPuIFdvVp7LCTpT+c",
  watchers: [
    node: ["pre-build.js", cd: Path.expand("../assets", __DIR__)],
    node: ["build.js", "--watch", cd: Path.expand("../assets", __DIR__)],
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
config :harpoon, HarpoonWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/harpoon_web/(controllers|live|components)/.*(ex|heex)$"
    ]

    # ## SSL Support
    #
    # In order to use HTTPS in development, a self-signed
    # certificate can be generated by running the following
    # Mix task:
  ]

# Do not include metadata nor timestamps in development logs
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#
# The `http:` config above can be replaced with:
#
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
#     https: [
# in production as building large stacktraces may be expensive.
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
config :phoenix, :stacktrace_depth, 20

# Include HEEx debug annotations as HTML comments in rendered markup
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

config :phoenix_live_view, :debug_heex_annotations, true
